apiVersion: security-profiles-operator.x-k8s.io/v1alpha1
kind: ProfileRecording
metadata:
  name: demo-recorder
spec:
  kind: SeccompProfile
  recorder: logs
  podSelector:
    matchLabels:
      app: demo